"""empty message

Revision ID: c8c01338dbc9
Revises: 
Create Date: 2023-11-02 10:19:18.114070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8c01338dbc9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person1_id', sa.Integer(), nullable=True),
    sa.Column('person2_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__relations'))
    )
    op.create_index(op.f('ix__relations__id'), 'relations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users'))
    )
    op.create_index(op.f('ix__users__email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix__users__id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix__users__login'), 'users', ['login'], unique=True)
    op.create_table('trees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('bg_img', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__trees__user_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__trees'))
    )
    op.create_index(op.f('ix__trees__id'), 'trees', ['id'], unique=False)
    op.create_index(op.f('ix__trees__token'), 'trees', ['token'], unique=True)
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('career', sa.String(), nullable=True),
    sa.Column('characters', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name=op.f('fk__persons__tree_id__trees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__persons'))
    )
    op.create_index(op.f('ix__persons__id'), 'persons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__persons__id'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix__trees__token'), table_name='trees')
    op.drop_index(op.f('ix__trees__id'), table_name='trees')
    op.drop_table('trees')
    op.drop_index(op.f('ix__users__login'), table_name='users')
    op.drop_index(op.f('ix__users__id'), table_name='users')
    op.drop_index(op.f('ix__users__email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix__relations__id'), table_name='relations')
    op.drop_table('relations')
    # ### end Alembic commands ###
